### ISSUE TITLE
What cookie bing, bro?

### ISSUE THREAD

**Issue by Juranik** [yihong0618/tg_bing_dalle#1]

**Comment by Juranik** [comment]
```
Sending request...
2023-10-14 18:57:11,682 (__init__.py:960 MainThread) ERROR - TeleBot: "Infinity polling exception: 'NoneType' object has no attribute 'extract_cookies'"
2023-10-14 18:57:11,683 (__init__.py:962 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 6766, in _run_middlewares_and_handler
    if self._test_message_handler(handler, message):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 6680, in _test_message_handler
    if not self._test_filter(message_filter, filter_value, message):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 6721, in _test_filter
    return filter_value(message)
  File "C:\Users\Administrator\Desktop\tg_bing_dalle-main\tg.py", line 32, in reply_dalle_image
    images = i.get_images(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\BingImageCreator.py", line 112, in get_images
    response = self.session.post(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 719, in send
    extract_cookies_to_jar(self.cookies, request, r.raw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 137, in extract_cookies_to_jar
    jar.extract_cookies(res, req)
AttributeError: 'NoneType' object has no attribute 'extract_cookies'
```

**Comment by Juranik** [comment]
YEah.....):

**Comment by yihong0618** [comment]
put the whole cookie as arg

**Comment by BeautyyuYanli** [comment]
@Juranik Follow the latest README

**Comment by BeautyyuYanli** [comment]
Does the problem still exists @Juranik ?

**Comment by yihong0618** [comment]
seems this issue is fixed
