### ISSUE TITLE
Process will crash if the OPENAI_API_KEY is not set

### ISSUE THREAD

**Issue by F4ria** [yihong0618/tg_bing_dalle#33]
When using the latest code, the following error occurs:
```
2023-11-07T09:17:51Z app[148e772c06d589] nrt [info]Traceback (most recent call last):
2023-11-07T09:17:51Z app[148e772c06d589] nrt [info]  File "/app/tg.py", line 11, in <module>
2023-11-07T09:17:51Z app[148e772c06d589] nrt [info]    from responder import respond_prompt, respond_quota
2023-11-07T09:17:51Z app[148e772c06d589] nrt [info]  File "/app/responder.py", line 10, in <module>
2023-11-07T09:17:51Z app[148e772c06d589] nrt [info]    from utils import get_quota, prepare_save_images, save_images
2023-11-07T09:17:51Z app[148e772c06d589] nrt [info]  File "/app/utils.py", line 8, in <module>
2023-11-07T09:17:51Z app[148e772c06d589] nrt [info]    client = OpenAI()
2023-11-07T09:17:51Z app[148e772c06d589] nrt [info]  File "/usr/local/lib/python3.10/site-packages/openai/_client.py", line 93, in __init__
2023-11-07T09:17:51Z app[148e772c06d589] nrt [info]    raise OpenAIError(
2023-11-07T09:17:51Z app[148e772c06d589] nrt [info]openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
2023-11-07T09:17:52Z app[148e772c06d589] nrt [info] INFO Main child exited normally with code: 1
```

**Comment by yihong0618** [comment]
shit my problem

**Comment by yihong0618** [comment]
will fix it

**Comment by crosspacific** [comment]
使用最新的版本，同样遇到相似问题：

Arg parse done.
Config parse done.
OpenAI init done.
Traceback (most recent call last):
  File "/root/tg_bing_dalle/tg.py", line 159, in <module>
    main()
  File "/root/tg_bing_dalle/tg.py", line 55, in main
    client = OpenAI()
  File "/root/.venv/lib/python3.9/site-packages/openai/_client.py", line 93, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

去掉 -c config.toml 才正常。

**Comment by yihong0618** [comment]
拉下最新代码
