### ISSUE TITLE
run error --- 'NoneType' object has no attribute 'extract_cookies'

### ISSUE THREAD

**Issue by burndown** [yihong0618/tg_bing_dalle#42]
更新完报错。
tg_toke 和 bing_cookie 都检查过了。
服务器在美国，应该不存在访问限制的问题。

```
heigao@bwg:~/tg_bing2/tg_bing_dalle$ python3 tg.py $tg_token $bing_cookie
Arg parse done.
Bot init done.
your 24 cookie is wrong please check error: 'NoneType' object has no attribute 'extract_cookies'
Traceback (most recent call last):
  File "/home/heigao/tg_bing2/tg_bing_dalle/tg.py", line 161, in <module>
    main()
  File "/home/heigao/tg_bing2/tg_bing_dalle/tg.py", line 81, in main
    image_obj.get_limit_left()
  File "/home/heigao/.local/lib/python3.10/site-packages/BingImageCreator.py", line 104, in get_limit_left
    r = self.session.get("https://www.bing.com/create")
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 557, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 673, in send
    extract_cookies_to_jar(self.cookies, request, r.raw)
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 132, in extract_cookies_to_jar
    jar.extract_cookies(res, req)
AttributeError: 'NoneType' object has no attribute 'extract_cookies'

heigao@bwg:~/tg_bing2/tg_bing_dalle$ echo $bing_cookie
_IDET=VSNoti2=20230306&MIExp=0; ipv6=hit=1700449202956&t=4; MUID=29740A3C59DC61AD0E8618FA58A6603E; SRCHD=AF=NOFORM; SRCHUID=V=2&GUID=71484B96A1B24033B0E4A37B7D0AB621&dmnchg=1; MUIDB=29740A3C59DC61AD0E8618FA58A6603E; _UR=QS=0&TQS=0; MMCASM=ID=A937CF8A3A334A8A848A2D6D6229A6E2; MicrosoftApplicationsTelemetryDeviceId=492bef10-8018-40c4-8e74-06787f6037df; EDGSRVCUSR=udscdxtone=Creative; PPLState=1; SnrOvr=X=rebateson; ABDEF=V=13&ABDV=11&MRNB=1679380599512&MRB=0; _HPVN=CS=eyJQbiI6eyJDbiI6MTUsIlN0IjowLCJRcyI6MCwiUHJvZCI6IlAifSwiU2MiOnsiQ24iOjE1LCJTdCI6MCwiUXMiOjAsIlByb2QiOiJIIn0sIlF6Ijp7IkNuIjoxNSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiVCJ9LCJBcCI6dHJ1ZSwiTXV0ZSI6dHJ1ZSwiTGFkIjoiMjAyMy0wNy0xN1QwMDowMDowMFoiLCJJb3RkIjowLCJHd2IiOjAsIkRmdCI6bnVsbCwiTXZzIjowLCJGbHQiOjAsIkltcCI6Mzl9; ANON=A=9DAEFFF4023744F603DA0EB7FFFFFFFF&E=1d05&W=2; NAP=V=1.9&E=1cab&C=3rHMjcRxzyBIOK1bfynCR1ORkTP9EqxQO_aCJOIUPYkOrGfcl4kAjQ&W=1; KievRPSSecAuth=FABqBBRaTOJILtFsMkpLVWSG6AN6C/svRwNmAAAEgAAACE6zQnbk/meNKAT9vDRpqQvNBd2S1HHFrQ6Sjcpt5jzWfIXJMI6AO4JSvJ8G85nVEaM8N2aDWMkUfMnprGRIyA0hI4m2ngi0EaHFjYtwV1hknuA0hSNJcYEurNStiM5sbbqDBPa2VpkOyTVSq84q2fgEONfigioTJT6qohSr7dRBEKOqEKLDJ4TM/2bluc6J4VI/9pFyefK03cdfATkwDj/itq8fKP0Si7y08NHB+/ODgfi+N5Y9FXcdbPJus7G1enzw2dqhL5F7m/zWhDh+baE9nxG+oe5tNuf2jrIx9clPJXwICird4+22JGu9J7hKITmGCoKONhO9YpwbFuWsEiUIsfmDfJhRlV+Wkwa0bb8ib15/WV3FHOCys3xuwNzw/Zr1h4eEqNDWPp2M64lZ0Z1ifyz15tjan4XWZ1B7G2eslqWUcEOjxesp9DikbsEMXiiKQcJiThwmXYrfYIuvCT5G0rFZrMLPf5dYxEjLTIAggaxU5wqa/SpSH+dP0hUZipl0nZlCj7KY77q49lTfxb7CBK8fIXUl86JDNl3NfOpl7nxdw7fwtPouHQ+KNAwHVNaPLd4S4K7KzgqMO9//Lanyp6XJ0ZlZfQ+wBU4ojHzTRVyet/4zh4++zY8GcH//7fDqbvjSHu4J2NTb+hdRP/cV0jE5KJsPR7nLYYoXocrXdqJEYbtWCESUrOqNMRVMzxS+bCTIPKI2bJdHhwreF3RLenopOEgdFSLy/wmIYTU+w6381/O7+KwU4QeXcNWkN1wuuFlROQbEfdr8baK00WzqWDf1w2xq4SD1nIDnRltVwErjsvkOVVmW7uXfnXjIiwFJ3HtHNest88nJUJxIRJALf2ODQYmWtUdiC7+6Q0pJEs901gH/6iIpKFRGHS597h7UszPcKZxnooDerZPEmA+ZoXQmhSPDYimQ37926pbNF3ZZoKUP58zCldibVghAHtobeoyDirNffwtQNLv1qRM86+OHiQ0eTIIStbfcAmPHNFe44Xz+DpmZchb+IQAlLmurwDSP4XzjBl/2uz+RJiC6bpKG3eHC43epcTkGKOOFkiFf0DlIqIC1kspvxwEjB4usbfShq05oli87zUSYZQPpg+xl2HVUdPxwMvGtomUyObfPXtP1qsFSo01NoWSHBiztiESfeDEu6tMdBVacbcbSkvlrkK/NelZ94kyfqv5KCKTA4pc6WAxDGAugzFjZvOtk8pFGbFaPbHbs3r4Hn5JkWEtscRM16/NLW31WNy7k3Y6We3KFTn8hLhF2PCx6z86DOSaUjPnLb/dv2Oq9WXV8+SFPu2R/AQ4KZAhGLLn6UWBmccEbQEGiFBWRP9QbhR0lCOfQLxW+wRg980XZ7XJwTOG+ZDHwmTFJOZPDre/xge9JwGKqI0dOv4S5Z6WSnPaD2jRqrg6qlLvlZARM89llKBQAd3Ek5FWEZlkaB05NcIGoFqgJ5go=; _U=1j49_vguHwhM0FRkS4TC4Btp9raEriOatBs3oHU_sWyIriiEpyCqI85zuY-SxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxLilpZyVGCBahbtsjZV2IEFq/1AlMLfMh6pE=; _clck=jvvs|2|fgj|0|1407; USRLOCxxxxxxxxxxxxxxxxxxxxxxxxx%98; SRCHUSR=DOB=20230316&T=1700445595000&POEX=W; _Rwho=u=d; _SS=SID=207DF0DD84DA6A740571E31285436B20&R=403&RB=403&GB=0&RG=0&RP=403; GI_FRE_COOKIE=gi_prompt=2&gi_sc=1; _RwBf=W=1&ilt=1&ihpd=0&ispd=1&rc=403&rb=403&gb=0&rg=0&pc=403&mtu=0&rbb=0.0&g=0&cid=&clo=0&v=2&l=2023-11-19T08:00:00.0000000Z&lft=0001-01-01T00:00:00.0000000&aof=0&o=0&p=bingcopilotwaitlist&c=MY00IA&t=1352&s=2023-02-08T00:22:22.3026774+00:00&ts=2023-11-20T02:00:11.6448886+00:00&rwred=0&wls=2&lka=0&lkt=0&TH=&r=1&mta=0&e=8bwyNw3ddMPGmdw4D3qRt3RsYdwQfVqNajmPcVziC6AfJo6e4sMW4PpVuxfc37L_IAzuLLUjS_O-CyckpihqSYg2P0GC-z2qkI5QolOb6iE&A=&mte=0&dci=0&wlb=0&aad=0; _EDGE_S=SID=207DF0DD84DA6A740571E31285436B20&mkt=en-us&ui=en-us; SRCHHPGUSR=SRCHLANG=en&DM=0&WTS=63825153443&PV=10.0.0&HV=1700179987&BRW=S&BRH=T&CW=1067&CH=1006&SCW=1067&SCH=1006&DPR=1.0&UTC=480&PRVCW=1912&PRVCH=1006&EXLTT=20&cdxtone=Creative&TH=ThRb&cdxts=1&PR=1.5&IG=C0471D71754247D2BB3B9372A396C13E&CIBV=1.1359.4

```

**Comment by yihong0618** [comment]
cookie 用引号包裹

**Comment by burndown** [comment]
搞定！
