### ISSUE TITLE
根据你提供的错误信息，看起来你的代码在使用 Telegram Bot API 时遇到了错误。  错误消息中提到了错误代码 429，这表示你的请求频率超过了 Telegram API 的限制，导致请求被拒绝。错误消息还提到了 `retry after 1682`，这表示你需要在稍后再次尝试发送请求，等待 1682 秒后再进行下一次请求。

### ISSUE THREAD

**Issue by cnmeeia** [yihong0618/tg_bing_dalle#50]
`/Users/mick/bing-bot/tg_bing_dalle/venv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Arg parse done.
Traceback (most recent call last):
  File "/Users/mick/bing-bot/tg_bing_dalle/tg.py", line 215, in <module>
    main()
  File "/Users/mick/bing-bot/tg_bing_dalle/tg.py", line 74, in main
    bot.delete_my_commands(scope=None, language_code=None)
  File "/Users/mick/bing-bot/tg_bing_dalle/venv/lib/python3.9/site-packages/telebot/__init__.py", line 3687, in delete_my_commands
    return apihelper.delete_my_commands(self.token, scope, language_code)
  File "/Users/mick/bing-bot/tg_bing_dalle/venv/lib/python3.9/site-packages/telebot/apihelper.py", line 1274, in delete_my_commands
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/mick/bing-bot/tg_bing_dalle/venv/lib/python3.9/site-packages/telebot/apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/mick/bing-bot/tg_bing_dalle/venv/lib/python3.9/site-packages/telebot/apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 429. Description: Too Many Requests: retry after 1682`

**Comment by yihong0618** [comment]
请确认你的终端能访问 google
curl google.com
